import mongoose from 'mongoose';

/**
 * Legal Document Schema
 * Stores metadata for ingested documents
 */
const legalDocumentSchema = new mongoose.Schema({
  // Unique identifier
  documentId: {
    type: String,
    required: true,
    unique: true,
    index: true
  },
  
  // Document info
  filename: {
    type: String,
    required: true
  },
  
  originalName: {
    type: String,
    required: true
  },
  
  fileType: {
    type: String,
    enum: ['pdf', 'txt', 'doc', 'docx'],
    required: true
  },
  
  fileSize: {
    type: Number,
    required: true
  },
  
  // Content metadata
  numPages: {
    type: Number,
    default: 1
  },
  
  numChunks: {
    type: Number,
    default: 0
  },
  
  // Legal document classification
  documentType: {
    type: String,
    enum: [
      'act',
      'amendment',
      'case_law',
      'judgment',
      'contract',
      'agreement',
      'petition',
      'notification',
      'circular',
      'guideline',
      'other'
    ],
    default: 'other'
  },
  
  // Jurisdiction info
  jurisdiction: {
    type: String,
    enum: ['india', 'us', 'uk', 'international', 'other'],
    default: 'india'
  },
  
  // Legal metadata
  legalMetadata: {
    actName: String,
    year: Number,
    sections: [String],
    court: String,
    caseNumber: String,
    parties: [String],
    judges: [String],
    dateOfJudgment: Date
  },
  
  // Extracted sections from document
  extractedSections: [{
    type: String,
    number: String,
    title: String,
    position: Number
  }],
  
  // Processing status
  status: {
    type: String,
    enum: ['pending', 'processing', 'indexed', 'failed'],
    default: 'pending'
  },
  
  processingError: String,
  
  // Timestamps
  uploadedAt: {
    type: Date,
    default: Date.now
  },
  
  indexedAt: Date,
  
  // User who uploaded (if auth is enabled)
  uploadedBy: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'User'
  },
  
  // Tags for categorization
  tags: [String],
  
  // Full text (for backup/re-indexing)
  fullText: String,
  
  // Summary generated by AI
  summary: String

}, {
  timestamps: true
});

// Indexes for efficient queries
legalDocumentSchema.index({ documentType: 1 });
legalDocumentSchema.index({ jurisdiction: 1 });
legalDocumentSchema.index({ status: 1 });
legalDocumentSchema.index({ 'legalMetadata.actName': 1 });
legalDocumentSchema.index({ 'legalMetadata.year': 1 });
legalDocumentSchema.index({ tags: 1 });
legalDocumentSchema.index({ createdAt: -1 });

// Text index for basic search
legalDocumentSchema.index({
  filename: 'text',
  originalName: 'text',
  'legalMetadata.actName': 'text',
  tags: 'text'
});

export const LegalDocument = mongoose.model('LegalDocument', legalDocumentSchema);

/**
 * Citation Schema
 * Tracks citations generated in responses
 */
const citationSchema = new mongoose.Schema({
  // Reference to the chat message
  messageId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Message'
  },
  
  chatId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Chat'
  },
  
  // Citation details
  citations: [{
    sourceNumber: Number,
    documentId: String,
    source: String,
    page: Number,
    section: String,
    excerpt: String,
    relevanceScore: Number
  }],
  
  // Query that generated these citations
  query: String,
  
  createdAt: {
    type: Date,
    default: Date.now
  }
});

citationSchema.index({ chatId: 1 });
citationSchema.index({ 'citations.documentId': 1 });

export const Citation = mongoose.model('Citation', citationSchema);

export default { LegalDocument, Citation };
